_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "pretrained/swin_tiny_patch4_window7_224_converted.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  BACKBONE:
    NAME: "build_swint_fpn_backbone"
    FREEZE_AT: -1 #NOTE: swinT specifc
  SWINT:
    OUT_FEATURES: ["stage2", "stage3", "stage4", "stage5"] #NOTE: swinT specifc
  FPN:
    IN_FEATURES: ["stage2", "stage3", "stage4", "stage5"] #NOTE: swinT specifc
    TOP_LEVELS: 2 #NOTE: swinT specifc
  DISTILLATOR:
    TEACHER:
        META_ARCH: 'DynamicTeacher'
        SOLVER:
            OPTIMIZER: 'SGD'
            BASE_LR: 0.02
            MOMENTUM: 0.9
            WEIGHT_DECAY: 1e-4
            LR_SCHEDULER_NAME: "WarmupMultiStepLR"
            STEPS: (12000, 16000)
            GAMMA: 0.1
            WARMUP_FACTOR: 1e-3
            WARMUP_ITERS:  1e03
            WARMUP_METHOD: "linear"
        INTERACT_PATTERN: 'stuGuided'
        DETACH_APPEARANCE_EMBED: True
        ADD_CONTEXT_BOX: False
    STUDENT:
        META_ARCH: 'RCNNCT'
        SOLVER:
            OPTIMIZER: 'SGD'
            BASE_LR: 0.02
            MOMENTUM: 0.9
            WEIGHT_DECAY: 1e-4
            LR_SCHEDULER_NAME: "WarmupMultiStepLR"
            STEPS: (12000, 16000)
            GAMMA: 0.1
            WARMUP_FACTOR: 1e-3
            WARMUP_ITERS:  1e03
            WARMUP_METHOD: "linear"
    ADAPTER:
        META_ARCH: 'SequentialConvs'
    PRE_NONDISTILL_ITERS: 3000
    PRE_FREEZE_STUDENT_BACKBONE_ITERS: 2000
    LAMBDA: 1.0

    # ====================================
    # 损失函数的配置
    # LAMBDA: 0.2
    # # LAMBDA: 1000000.0
    # DISTILLER: 'cwd'
    # # DISTILLER: 'mimic'
    # # DISTILLER: 'mgd'
    # ====================================
    EVAL_TEACHER: True
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.01
  STEPS: (12000, 16000)
  MAX_ITER: 18000
  CHECKPOINT_PERIOD: 2000
TEST:
  EVAL_PERIOD: 2000
INPUT:
  MAX_SIZE_TRAIN: 700
  MIN_SIZE_TRAIN: 512
  MAX_SIZE_TEST: 700
  MIN_SIZE_TEST: 512

OUTPUT_DIR: 'outputs/FasterRCNN/faster_rcnn_SwinT_Tiny_2xMS_stuGuided_addCtxBox=NO_detachAppearanceEmbed=YES_preNondistillIters=30k_preFreezeStudentBackboneIters=20k'
